app = "mamacare-api"
primary_region = "fra"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 1
