name: Fly Deploy
permissions:
  contents: read
on:
  pull_request:
    branches: ["*"]
    paths:
      - apps/api/**
      - packages/**
      - patches/**
  push:
    branches: ["main"]
    paths:
      - apps/api/**
      - packages/**
      - patches/**
jobs:
  deploy:
    name: 🚀 Deploy to Fly Preview
    runs-on: ubuntu-latest
    concurrency: fly-preview
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: 🔦 Run linter
        run: bun run lint
        working-directory: ./apps/api
      - name: 🪐 Check TypeScript
        run: bun run typecheck
        working-directory: ./apps/api
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only --dockerfile apps/api/Dockerfile --config apps/api/fly-preview.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
